In [15]:
import requests
import pandas as pd

# URL base de la API para obtener indicadores
base_url = 'https://api.worldbank.org/v2/indicators'
params = {
    'format': 'json',
    'per_page': 10000  # Número de resultados por página, máximo permitido por la API
}

# Lista para almacenar todos los indicadores
all_indicators = []

page = 1
while True:
    params['page'] = page
    response = requests.get(base_url, params=params)
    data = response.json()

    # Añadir los indicadores a la lista
    indicators = data[1]
    all_indicators.extend(indicators)
    
    # Verificar si hay más páginas
    if len(indicators) == 0:
        break
    
    page += 1

# Convertir la lista de indicadores en un DataFrame de Pandas
df_indicators = pd.DataFrame(all_indicators)

# Mostrar los primeros registros del DataFrame
print(df_indicators.head())

# Guardar los indicadores en un archivo CSV
df_indicators.to_csv('worldbank_indicators.csv', index=False)

                     id                                     name unit  \
0    1.0.HCount.1.90usd          Poverty Headcount ($1.90 a day)
1     1.0.HCount.2.5usd          Poverty Headcount ($2.50 a day)
2  1.0.HCount.Mid10to50    Middle Class ($10-50 a day) Headcount
3       1.0.HCount.Ofcl  Official Moderate Poverty Rate-National
4   1.0.HCount.Poor4uds             Poverty Headcount ($4 a day)

                                    source  \
0  {'id': '37', 'value': 'LAC Equity Lab'}
1  {'id': '37', 'value': 'LAC Equity Lab'}
2  {'id': '37', 'value': 'LAC Equity Lab'}
3  {'id': '37', 'value': 'LAC Equity Lab'}
4  {'id': '37', 'value': 'LAC Equity Lab'}

                                          sourceNote  \
0  The poverty headcount index measures the propo...
1  The poverty headcount index measures the propo...
2  The poverty headcount index measures the propo...
3  The poverty headcount index measures the propo...
4  The poverty headcount index measures the propo...

                                  sourceOrganization  \
0  LAC Equity Lab tabulations of SEDLAC (CEDLAS a...
1  LAC Equity Lab tabulations of SEDLAC (CEDLAS a...
2  LAC Equity Lab tabulations of SEDLAC (CEDLAS a...
3  LAC Equity Lab tabulations of data from Nation...
4  LAC Equity Lab tabulations of SEDLAC (CEDLAS a...

                                topics
0  [{'id': '11', 'value': 'Poverty '}]
1  [{'id': '11', 'value': 'Poverty '}]
2  [{'id': '11', 'value': 'Poverty '}]
3  [{'id': '11', 'value': 'Poverty '}]
4  [{'id': '11', 'value': 'Poverty '}]

In [16]:
df = pd.read_csv('worldbank_indicators.csv')
df

,id,name,unit,source,sourceNote,sourceOrganization,topics
0,1.0.HCount.1.90usd,Poverty Headcount ($1.90 a day),NaN,"{'id': '37', 'value': 'LAC Equity Lab'}",The poverty headcount index measures the propo...,LAC Equity Lab tabulations of SEDLAC (CEDLAS a...,"[{'id': '11', 'value': 'Poverty '}]"
1,1.0.HCount.2.5usd,Poverty Headcount ($2.50 a day),NaN,"{'id': '37', 'value': 'LAC Equity Lab'}",The poverty headcount index measures the propo...,LAC Equity Lab tabulations of SEDLAC (CEDLAS a...,"[{'id': '11', 'value': 'Poverty '}]"
2,1.0.HCount.Mid10to50,Middle Class ($10-50 a day) Headcount,NaN,"{'id': '37', 'value': 'LAC Equity Lab'}",The poverty headcount index measures the propo...,LAC Equity Lab tabulations of SEDLAC (CEDLAS a...,"[{'id': '11', 'value': 'Poverty '}]"
3,1.0.HCount.Ofcl,Official Moderate Poverty Rate-National,NaN,"{'id': '37', 'value': 'LAC Equity Lab'}",The poverty headcount index measures the propo...,LAC Equity Lab tabulations of data from Nation...,"[{'id': '11', 'value': 'Poverty '}]"
4,1.0.HCount.Poor4uds,Poverty Headcount ($4 a day),NaN,"{'id': '37', 'value': 'LAC Equity Lab'}",The poverty headcount index measures the propo...,LAC Equity Lab tabulations of SEDLAC (CEDLAS a...,"[{'id': '11', 'value': 'Poverty '}]"

In [32]:
url = 'https://api.worldbank.org/v2/country/ZMB/indicators/NY.GDP.MKTP.CD'
params = {
    'format' : 'json'
}
data = requests.get(url, params=params).json()
for year in data[1]:
    print(year['date'],' --- ',year['value'],'$')

2023  ---  28162630953.9285 $
2022  ---  29163782140.4858 $
2021  ---  22096416932.0089 $
2020  ---  18137764931.2808 $
2019  ---  23308667781.2258 $
2018  ---  26311507273.6735 $
2017  ---  25873601260.8353 $
2016  ---  20958412538.3093 $
2015  ---  21251216798.7762 $
2014  ---  27141023558.0829 $
2013  ---  28037239462.7142 $
2012  ---  25503060420.026 $
2011  ---  23459515275.5776 $
2010  ---  20265559483.8548 $
2009  ---  15328342303.9575 $
2008  ---  17910858637.9048 $
2007  ---  14056957976.2648 $
2006  ---  12756858899.2812 $
2005  ---  8331870169.14977 $
2004  ---  6221110219.45542 $
2003  ---  4901869764.05957 $
2002  ---  4193850445.42632 $
2001  ---  4094441301.21423 $
2000  ---  3600632111.41414 $
1999  ---  3404284890.5306 $
1998  ---  3537741941.89367 $
1997  ---  4303288479.7086 $
1996  ---  3597220962.00017 $
1995  ---  3806983413.16416 $
1994  ---  3656806165.78848 $
1993  ---  3273505343.85539 $
1992  ---  3181921787.7095 $
1991  ---  3376791460.39604 $
1990  ---  3285217391.30435 $
1989  ---  3994585203.41682 $
1988  ---  3728889426.56666 $
1987  ---  2265364008.82446 $
1986  ---  1664509501.79764 $
1985  ---  2252197452.2293 $
1984  ---  2719801434.08715 $
1983  ---  3321048451.15171 $
1982  ---  3870075349.83854 $
1981  ---  4006206896.55172 $
1980  ---  3882889733.8403 $
1979  ---  3354854981.08449 $
1978  ---  2809862671.66042 $
1977  ---  2514430379.74684 $
1976  ---  2742796005.70613 $
1975  ---  2443545878.69362 $
1974  ---  2913063763.60809 $